services:
  servidor:
    container_name: backend
    build:
      context: backend/manual 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    depends_on: 
      - db 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create    
    networks: 
      - backend
      - frontend
  cliente:
    container_name: frontend
    build:
      context:  frontend 
      dockerfile: Dockerfile
      args:
        API_BASE_URL: http://127.0.0.1:8080
    ports:
      - "3000:80" 
    depends_on:
      - servidor
    networks:
      - frontend  

  db:
    container_name: PostgreSQL
    image: 'postgres:13.4-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=api
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - backend  
volumes:
  db-data:

networks:
  backend:
  frontend:    